In [1]:
import numpy as np #Import Python Library (This is where the data is stored and pulled from the csv)
import pandas as pd # Import software library (This is a software library written for python) This library is used for data manipulation and analysis
import scipy.stats as stats #Import python library (This is used for scientific computations)

In [2]:
data0 = np.genfromtxt('gen_xyz_raw_spec_as_int.csv',delimiter = ',', skip_header = 1)  # This generates data from the csv text
data0 = pd.DataFrame(data0) # This arranges the csv data into an object that pandas can use
data = data0.drop(data0.columns[0:4],axis = 1) # This removes the first three columns: plant number, plant species, and plant species as
                                               # an integer;these will be added back in the final step

In [3]:
data

,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22
0,94.737452,196.644672,1776.847433,14.015541,6214.957396,1986.070463,18823.600570,5107.996944,45.755582,191.923742,0.081735,0.811444,33.255243,95.859746,0.005128,16.256776,5.981147,0.278855,0.024450
1,23.352362,131.009202,1166.801218,15.981347,5660.589666,1305.737926,15284.870700,3971.658387,40.226177,101.724123,0.048140,0.343131,33.814473,69.386864,0.017477,7.492277,3.537671,0.156314,0.060345
2,137.680886,111.022071,1976.897836,26.302390,7208.531961,2512.636791,20787.041280,5653.053084,65.567369,146.973893,0.063966,0.277827,58.400894,83.124578,0.004849,7.214685,3.383637,0.297982,0.017739
3,18.207032,58.447077,1469.811734,24.007341,5342.222323,2400.683753,16094.439100,3800.777526,60.854345,218.874289,0.099867,0.416359,55.600415,120.534218,0.010221,11.923196,1.183187,0.171235,0.038915
4,58.775194,119.388231,1349.136877,67.323999,5412.124249,2412.665543,17162.724580,2307.560196,91.539069,357.633934,0.169915,0.658896,68.828553,153.686687,0.060230,7.493530,1.004368,0.194630,0.021889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628,63.271123,120.320006,3246.471520,30.593269,6859.624191,2455.140922,6280.814932,19352.973150,104.939138,609.731883,0.315739,0.527004,22.211630,131.008992,0.029787,0.871185,21.618330,0.313928,0.038687
629,68.149793,50.617972,3978.041214,13.572751,3208.378200,2040.305333,9696.674618,26987.911380,64.032527,489.510388,0.186140,0.507425,25.588867,108.438684,0.007301,0.714012,32.160224,0.621919,0.027936
630,79.845844,114.880523,3771.860854,29.864188,3659.998036,3718.235500,7634.287244,33223.989900,129.796944,1365.772112,0.390680,1.176409,44.710243,172.768967,0.049686,0.350349,35.879156,0.068933,0.074695
631,76.601524,129.989238,2828.269118,42.094232,4336.275136,1450.279245,6126.337671,24461.875180,101.087531,532.239430,0.209278,0.581932,31.203185,129.128085,0.030015,1.883008,84.520866,0.885815,0.025436
632,53.130018,85.774245,2258.882091,20.433157,3499.544103,2884.711660,7453.720407,16177.024040,73.561312,695.721962,0.230524,0.599777,37.222041,155.769121,0.021495,0.482853,18.136362,0.058265,0.033991

In [6]:
z = pd.DataFrame(np.arange(14559).reshape(633,23)) #This creates a dummy dataframe for our z value
z = z.astype('float32') #Float is used when storing data with decimal points to keep it precise 
z.drop(z.columns[0:4],axis = 1, inplace = True ) #This drops three columns in our dummy dataframe
z

,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22
0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0,21.0,22.0
1,27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0,40.0,41.0,42.0,43.0,44.0,45.0
2,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0,60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0
3,73.0,74.0,75.0,76.0,77.0,78.0,79.0,80.0,81.0,82.0,83.0,84.0,85.0,86.0,87.0,88.0,89.0,90.0,91.0
4,96.0,97.0,98.0,99.0,100.0,101.0,102.0,103.0,104.0,105.0,106.0,107.0,108.0,109.0,110.0,111.0,112.0,113.0,114.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628,14448.0,14449.0,14450.0,14451.0,14452.0,14453.0,14454.0,14455.0,14456.0,14457.0,14458.0,14459.0,14460.0,14461.0,14462.0,14463.0,14464.0,14465.0,14466.0
629,14471.0,14472.0,14473.0,14474.0,14475.0,14476.0,14477.0,14478.0,14479.0,14480.0,14481.0,14482.0,14483.0,14484.0,14485.0,14486.0,14487.0,14488.0,14489.0
630,14494.0,14495.0,14496.0,14497.0,14498.0,14499.0,14500.0,14501.0,14502.0,14503.0,14504.0,14505.0,14506.0,14507.0,14508.0,14509.0,14510.0,14511.0,14512.0
631,14517.0,14518.0,14519.0,14520.0,14521.0,14522.0,14523.0,14524.0,14525.0,14526.0,14527.0,14528.0,14529.0,14530.0,14531.0,14532.0,14533.0,14534.0,14535.0
632,14540.0,14541.0,14542.0,14543.0,14544.0,14545.0,14546.0,14547.0,14548.0,14549.0,14550.0,14551.0,14552.0,14553.0,14554.0,14555.0,14556.0,14557.0,14558.0

In [7]:
for x in range(4,(data.shape[1]+4)): #This gives the dimensions of the array along the x axis
    mean = data[x].mean() #This gives the average of one column of data on the x axis
    stdev = data[x].std() #This gives the standard deviation of one column of the the x axis
    print(x,"m: ",mean,"s: ",stdev) #This prints the mean and standard deviation of the individual columns
    for y in range(data.shape[0]): #This gives the dimension of the array along the y axis
        zscore = (data[x][y] - mean)/stdev #This is the equation that gives us the z score
        z[x][y] = zscore #Assigning the name zscore to the value obtained from the equation
        if data[x][y] < 0: #If the data obtained is less than zero
            z[x][y] = "NaN" #Then it is not treated as a number
z

4 m:  87.98397074406007 s:  47.461746515669
5 m:  131.76946655595592 s:  114.05007256362457
6 m:  2326.792310815009 s:  1173.793442589106
7 m:  19.21610216050236 s:  14.396604798197275
8 m:  4919.316012625592 s:  1513.363048226687
9 m:  2587.3368692906793 s:  691.1888149167568
10 m:  13435.43231214851 s:  4594.912567615371
11 m:  13088.839174357043 s:  8918.772951679648
12 m:  71.568199193902 s:  34.819237555775125
13 m:  477.2883456176142 s:  311.4130523871865
14 m:  0.18296360702527648 s:  0.10379410308575979
15 m:  1.0089196485797784 s:  1.5892637892204715
16 m:  51.83189361710901 s:  31.636971070474356
17 m:  125.68873473502379 s:  68.91484312560358
18 m:  0.0179873244249605 s:  0.01831895223058937
19 m:  3.2159433719905226 s:  2.9816101412495812
20 m:  15.030399643450233 s:  12.30289418359028
21 m:  0.4073054468246446 s:  0.43434732544104543
22 m:  0.03545178467930494 s:  0.05497901835698941

,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22
0,0.142293,0.568831,-0.468519,-0.361235,0.856134,-0.869902,1.172638,-0.894836,-0.741332,-0.916354,-0.975281,-0.124256,-0.587182,-0.432838,-0.701978,4.373755,-0.735539,-0.295731,-0.200111
1,-1.361762,-0.006666,-0.988241,-0.224689,0.489819,-1.854195,0.402497,-1.022246,-0.900135,-1.206000,-1.298955,-0.418929,-0.569505,-0.816977,-0.027840,1.434236,-0.934148,-0.577859,0.452770
2,1.047094,-0.181915,-0.298089,0.492219,1.512668,-0.108075,1.599945,-0.833723,-0.172342,-1.060696,-1.146480,-0.460020,0.207637,-0.617634,-0.717192,1.341135,-0.946669,-0.251696,-0.322177
3,-1.470172,-0.642896,-0.730095,0.332803,0.279448,-0.270047,0.578685,-1.041406,-0.307699,-0.829811,-0.800586,-0.372852,0.119118,-0.074795,-0.423953,2.920319,-1.125525,-0.543505,0.062984
4,-0.615417,-0.108560,-0.832902,3.341614,0.325638,-0.252711,0.811178,-1.208830,0.573559,-0.384231,-0.125721,-0.220242,0.537240,0.406269,2.305948,1.434657,-1.140059,-0.489643,-0.246698
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628,-0.520690,-0.100390,0.783510,0.790267,1.282117,-0.191259,-1.557074,0.702354,0.958405,0.425299,1.279215,-0.303232,-0.936255,0.077200,0.644139,-0.786407,0.535478,-0.214982,0.058838
629,-0.417898,-0.711543,1.406763,-0.391992,-1.130553,-0.791436,-0.813673,1.558406,-0.216423,0.039247,0.030601,-0.315551,-0.829505,-0.250310,-0.583344,-0.839121,1.392341,0.494105,-0.136710
630,-0.171467,-0.148084,1.231110,0.739625,-0.832132,1.636165,-1.262515,2.257614,1.672315,2.853072,2.001235,0.105388,-0.225105,0.683165,1.730367,-0.961090,1.694622,-0.779037,0.713794
631,-0.239824,-0.015609,0.427227,1.589134,-0.385262,-1.645075,-1.590693,1.275180,0.847788,0.176457,0.253527,-0.268670,-0.652044,0.049907,0.656558,-0.447052,5.648303,1.101674,-0.182167
632,-0.734359,-0.403290,-0.057855,0.084538,-0.938157,0.430237,-1.301812,0.346257,0.057242,0.701427,0.458223,-0.257441,-0.461797,0.436486,0.191478,-0.916649,0.252458,-0.803596,-0.026577

In [8]:
f = pd.DataFrame(np.arange(14559).reshape(633,23))    
f = f.astype(str) #This coverts the data into a string
f[0] = data0[0] #This means that column zero in dataframe f is coulmn zero in dataframe zero
f[1] = data0[1] #This means that column one in dataframe f is column one in dataframe zero
for x in range(4,(z.shape[1])+4): #Counts through columns
    f[x] = z[x] #Adds back the original three columns dropped and the transformed data
f

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,318684.0,NaN,2,3,0.142293,0.568831,-0.468519,-0.361235,0.856134,-0.869902,...,-0.916354,-0.975281,-0.124256,-0.587182,-0.432838,-0.701978,4.373755,-0.735539,-0.295731,-0.200111
1,588141.0,NaN,25,26,-1.361762,-0.006666,-0.988241,-0.224689,0.489819,-1.854195,...,-1.206000,-1.298955,-0.418929,-0.569505,-0.816977,-0.027840,1.434236,-0.934148,-0.577859,0.452770
2,588646.0,NaN,48,49,1.047094,-0.181915,-0.298089,0.492219,1.512668,-0.108075,...,-1.060696,-1.146480,-0.460020,0.207637,-0.617634,-0.717192,1.341135,-0.946669,-0.251696,-0.322177
3,588448.0,NaN,71,72,-1.470172,-0.642896,-0.730095,0.332803,0.279448,-0.270047,...,-0.829811,-0.800586,-0.372852,0.119118,-0.074795,-0.423953,2.920319,-1.125525,-0.543505,0.062984
4,1583.0,NaN,94,95,-0.615417,-0.108560,-0.832902,3.341614,0.325638,-0.252711,...,-0.384231,-0.125721,-0.220242,0.537240,0.406269,2.305948,1.434657,-1.140059,-0.489643,-0.246698
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628,588392.0,NaN,14446,14447,-0.520690,-0.100390,0.783510,0.790267,1.282117,-0.191259,...,0.425299,1.279215,-0.303232,-0.936255,0.077200,0.644139,-0.786407,0.535478,-0.214982,0.058838
629,588391.0,NaN,14469,14470,-0.417898,-0.711543,1.406763,-0.391992,-1.130553,-0.791436,...,0.039247,0.030601,-0.315551,-0.829505,-0.250310,-0.583344,-0.839121,1.392341,0.494105,-0.136710
630,588371.0,NaN,14492,14493,-0.171467,-0.148084,1.231110,0.739625,-0.832132,1.636165,...,2.853072,2.001235,0.105388,-0.225105,0.683165,1.730367,-0.961090,1.694622,-0.779037,0.713794
631,588149.0,NaN,14515,14516,-0.239824,-0.015609,0.427227,1.589134,-0.385262,-1.645075,...,0.176457,0.253527,-0.268670,-0.652044,0.049907,0.656558,-0.447052,5.648303,1.101674,-0.182167
632,588257.0,NaN,14538,14539,-0.734359,-0.403290,-0.057855,0.084538,-0.938157,0.430237,...,0.701427,0.458223,-0.257441,-0.461797,0.436486,0.191478,-0.916649,0.252458,-0.803596,-0.026577

In [9]:
f.to_csv('geneva_xyz_transformed.csv',header = ('INVO', 'genus_species','spec_as_int','shoot_pos','B11','Na23','Mg26','Al27','P31','S34','K39','Ca44','Fe54','Mn55','Co59','Ni60','Cu63',
                                         'Zn66','As75','Rb85','Sr88','Mo98','Cd111'))