In [1]:
import numpy as np #Import Python Library (This is where the data is stored and pulled from the csv)
import pandas as pd # Import software library (This is a software library written for python) This library is used for data manipulation and analysis
import matplotlib.pyplot as plt #Import plotting library (This is used to display graphical data)
import scipy.stats as stats #Import python library (This is used for scientific computations)

In [2]:
data0 = np.genfromtxt('geneva_z_raw_spec_as_int.csv',delimiter = ',', skip_header = 1)  # This generates data from the csv text
data0 = pd.DataFrame(data0) # This arranges the csv data into an object that pandas can use
data = data0.drop(data0.columns[0:3],axis = 1) # This removes the first three columns: plant number, plant species, and plant species as
                                               # an integer;these will be added back in the final step

In [3]:
data

,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
0,75.649837,239.783324,3694.495174,26.954521,1696.651865,2342.846773,10844.525770,25804.62520,71.215486,1053.678753,0.346976,0.854512,17.502683,173.651460,0.015994,3.405492,40.071653,0.207729,0.038481
1,80.703292,186.700348,5272.952628,27.332428,2874.830875,2619.560521,4439.195121,21781.91107,111.531962,971.632025,0.303920,0.653269,33.540070,166.042457,0.026768,0.797610,39.555675,0.385602,0.044398
2,64.613696,82.762535,4810.860542,31.539338,6719.389066,2959.531369,10286.453500,26848.07659,118.291303,718.672696,0.216677,0.459874,39.773775,142.738457,0.022345,1.138830,30.526020,0.603184,0.036700
3,65.268254,126.855712,4155.981678,31.633060,4043.255680,2038.467250,4956.167866,19014.47633,89.821837,802.953098,0.198971,0.371279,15.532497,144.923406,0.026359,0.877615,18.750390,0.267194,0.035098
4,107.364963,164.496026,2852.011467,44.532515,2539.038881,3144.883915,4865.589820,19274.51258,168.161673,768.216649,0.322162,0.725153,21.697605,138.732870,0.037928,2.027483,21.487108,0.492434,0.036243
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,63.271123,120.320006,3246.471520,30.593269,6859.624191,2455.140922,6280.814932,19352.97315,104.939138,609.731883,0.315739,0.527004,22.211630,131.008992,0.029787,0.871185,21.618330,0.313928,0.038687
210,68.149793,50.617972,3978.041214,13.572751,3208.378200,2040.305333,9696.674618,26987.91138,64.032527,489.510388,0.186140,0.507425,25.588867,108.438684,0.007301,0.714012,32.160224,0.621919,0.027936
211,79.845844,114.880523,3771.860854,29.864188,3659.998036,3718.235500,7634.287244,33223.98990,129.796944,1365.772112,0.390680,1.176409,44.710243,172.768967,0.049686,0.350349,35.879156,0.068933,0.074695
212,76.601524,129.989238,2828.269118,42.094232,4336.275136,1450.279245,6126.337671,24461.87518,101.087531,532.239430,0.209278,0.581932,31.203185,129.128085,0.030015,1.883008,84.520866,0.885815,0.025436
213,53.130018,85.774245,2258.882091,20.433157,3499.544103,2884.711660,7453.720407,16177.02404,73.561312,695.721962,0.230524,0.599777,37.222041,155.769121,0.021495,0.482853,18.136362,0.058265,0.033991

In [4]:
z = pd.DataFrame(np.arange(4708).reshape(214,22)) #This creates a dummy dataframe for our z value
z = z.astype('float32') #Float is used when storing data with decimal points to keep it precise 
z.drop(z.columns[0:3],axis = 1, inplace = True ) #This drops three columns in our dummy dataframe
z

,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0,21.0
1,25.0,26.0,27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0,40.0,41.0,42.0,43.0
2,47.0,48.0,49.0,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0,60.0,61.0,62.0,63.0,64.0,65.0
3,69.0,70.0,71.0,72.0,73.0,74.0,75.0,76.0,77.0,78.0,79.0,80.0,81.0,82.0,83.0,84.0,85.0,86.0,87.0
4,91.0,92.0,93.0,94.0,95.0,96.0,97.0,98.0,99.0,100.0,101.0,102.0,103.0,104.0,105.0,106.0,107.0,108.0,109.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,4601.0,4602.0,4603.0,4604.0,4605.0,4606.0,4607.0,4608.0,4609.0,4610.0,4611.0,4612.0,4613.0,4614.0,4615.0,4616.0,4617.0,4618.0,4619.0
210,4623.0,4624.0,4625.0,4626.0,4627.0,4628.0,4629.0,4630.0,4631.0,4632.0,4633.0,4634.0,4635.0,4636.0,4637.0,4638.0,4639.0,4640.0,4641.0
211,4645.0,4646.0,4647.0,4648.0,4649.0,4650.0,4651.0,4652.0,4653.0,4654.0,4655.0,4656.0,4657.0,4658.0,4659.0,4660.0,4661.0,4662.0,4663.0
212,4667.0,4668.0,4669.0,4670.0,4671.0,4672.0,4673.0,4674.0,4675.0,4676.0,4677.0,4678.0,4679.0,4680.0,4681.0,4682.0,4683.0,4684.0,4685.0
213,4689.0,4690.0,4691.0,4692.0,4693.0,4694.0,4695.0,4696.0,4697.0,4698.0,4699.0,4700.0,4701.0,4702.0,4703.0,4704.0,4705.0,4706.0,4707.0

In [5]:
for x in range(3,(data.shape[1]+3)): #This gives the dimensions of the array along the x axis
    mean = data[x].mean() #This gives the average of one column of data on the x axis
    stdev = data[x].std() #This gives the standard deviation of one column of the the x axis
    print(x,"m: ",mean,"s: ",stdev) #This prints the mean and standard deviation of the individual columns
    for y in range(data.shape[0]): #This gives the dimension of the array along the y axis
        zscore = (data[x][y] - mean)/stdev #This is the equation that gives us the z score
        z[x][y] = zscore #Assigning the name zscore to the value obtained from the equation
        if data[x][y] < 0: #If the data obtained is less than zero
            z[x][y] = "NaN" #Then it is not treated as a number
z

3 m:  82.974160698785 s:  28.246254674514105
4 m:  103.45431591528039 s:  56.596342605142745
5 m:  3555.017346467291 s:  1217.7451013410814
6 m:  25.949479237070097 s:  11.313495597758141
7 m:  4306.847965495326 s:  1896.3618995346192
8 m:  2922.8726790233627 s:  826.6160852405051
9 m:  9331.99056380374 s:  4020.944596120608
10 m:  23338.428413612164 s:  6918.883860592174
11 m:  101.22238100528043 s:  40.696122051008146
12 m:  818.922063803271 s:  280.3614423936196
13 m:  0.28267024228971943 s:  0.09702594422333993
14 m:  1.2495760005186916 s:  2.2355977205455466
15 m:  41.49988914200932 s:  31.01564171155971
16 m:  161.0754185947196 s:  54.90923240916081
17 m:  0.024341156417840376 s:  0.013777113325078529
18 m:  1.1021294772710284 s:  0.8204823971980859
19 m:  28.385257734345803 s:  10.777039743833228
20 m:  0.515018174359813 s:  0.5743212284654936
21 m:  0.046338369355140165 s:  0.08909097064545965

,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
0,-0.259302,2.408795,0.114538,0.088836,-1.376423,-0.701687,0.376164,0.356444,-0.737340,0.837336,0.662771,-0.176715,-0.773713,0.229033,-0.605875,2.807328,1.084379,-0.535047,-0.088195
1,-0.080395,1.470873,1.410751,0.122239,-0.755139,-0.366932,-1.216827,-0.224967,0.253331,0.544690,0.219010,-0.266733,-0.256639,0.090459,0.176131,-0.371147,1.036502,-0.225338,-0.021783
2,-0.650014,-0.365603,1.031286,0.494088,1.272195,0.044348,0.237373,0.507256,0.419424,-0.357572,-0.680163,-0.353240,-0.055653,-0.333950,-0.144909,0.044730,0.198641,0.153513,-0.108190
3,-0.626841,0.413479,0.493506,0.502372,-0.138999,-1.069911,-1.088257,-0.624949,-0.280138,-0.056958,-0.862644,-0.392869,-0.837235,-0.294158,0.146494,-0.273637,-0.894018,-0.431509,-0.126167
4,0.863506,1.078545,-0.577301,1.642555,-0.932211,0.268578,-1.110784,-0.587366,1.644857,-0.180857,0.407025,-0.234578,-0.638461,-0.406900,0.986213,1.127817,-0.640078,-0.039324,-0.113319
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,-0.697545,0.298000,-0.253375,0.410465,1.346144,-0.565839,-0.758821,-0.576026,0.091330,-0.746145,0.340819,-0.323212,-0.621888,-0.547566,0.395302,-0.281474,-0.627902,-0.350135,-0.085887
210,-0.524826,-0.933565,0.347383,-1.093979,-0.579251,-1.067687,0.090696,0.527467,-0.913843,-1.174954,-0.994893,-0.331970,-0.513000,-0.958614,-1.236840,-0.473036,0.350279,0.186134,-0.206561
211,-0.110752,0.201889,0.178070,0.346021,-0.341100,0.962191,-0.422215,1.428780,0.702145,1.950518,1.113205,-0.032728,0.103508,0.212961,1.839622,-0.916267,0.695358,-0.776718,0.318294
212,-0.225610,0.468845,-0.596798,1.427035,0.015518,-1.781472,-0.797239,0.162374,-0.003314,-1.022547,-0.756416,-0.298642,-0.331984,-0.581821,0.411816,0.951731,5.208815,0.645626,-0.234613
213,-1.056570,-0.312389,-1.064373,-0.487588,-0.425712,-0.046165,-0.467122,-1.035052,-0.679698,-0.439433,-0.537441,-0.290660,-0.137926,-0.096638,-0.206585,-0.754772,-0.950994,-0.795291,-0.138598

In [6]:
f = pd.DataFrame(np.arange(4708).reshape(214,22))    
f = f.astype(str) #This coverts the data into a string
f[0] = data0[0] #This means that column zero in dataframe f is coulmn zero in dataframe zero
f[1] = data0[1] #This means that column one in dataframe f is column one in dataframe zero
for x in range(3,(z.shape[1])+3): #Counts through columns
    f[x] = z[x] #Adds back the original three columns dropped and the transformed data
f

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,318684.0,NaN,2,-0.259302,2.408795,0.114538,0.088836,-1.376423,-0.701687,0.376164,...,0.837336,0.662771,-0.176715,-0.773713,0.229033,-0.605875,2.807328,1.084379,-0.535047,-0.088195
1,588141.0,NaN,24,-0.080395,1.470873,1.410751,0.122239,-0.755139,-0.366932,-1.216827,...,0.544690,0.219010,-0.266733,-0.256639,0.090459,0.176131,-0.371147,1.036502,-0.225338,-0.021783
2,588646.0,NaN,46,-0.650014,-0.365603,1.031286,0.494088,1.272195,0.044348,0.237373,...,-0.357572,-0.680163,-0.353240,-0.055653,-0.333950,-0.144909,0.044730,0.198641,0.153513,-0.108190
3,588378.0,NaN,68,-0.626841,0.413479,0.493506,0.502372,-0.138999,-1.069911,-1.088257,...,-0.056958,-0.862644,-0.392869,-0.837235,-0.294158,0.146494,-0.273637,-0.894018,-0.431509,-0.126167
4,588459.0,NaN,90,0.863506,1.078545,-0.577301,1.642555,-0.932211,0.268578,-1.110784,...,-0.180857,0.407025,-0.234578,-0.638461,-0.406900,0.986213,1.127817,-0.640078,-0.039324,-0.113319
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,588392.0,NaN,4600,-0.697545,0.298000,-0.253375,0.410465,1.346144,-0.565839,-0.758821,...,-0.746145,0.340819,-0.323212,-0.621888,-0.547566,0.395302,-0.281474,-0.627902,-0.350135,-0.085887
210,588391.0,NaN,4622,-0.524826,-0.933565,0.347383,-1.093979,-0.579251,-1.067687,0.090696,...,-1.174954,-0.994893,-0.331970,-0.513000,-0.958614,-1.236840,-0.473036,0.350279,0.186134,-0.206561
211,588371.0,NaN,4644,-0.110752,0.201889,0.178070,0.346021,-0.341100,0.962191,-0.422215,...,1.950518,1.113205,-0.032728,0.103508,0.212961,1.839622,-0.916267,0.695358,-0.776718,0.318294
212,588149.0,NaN,4666,-0.225610,0.468845,-0.596798,1.427035,0.015518,-1.781472,-0.797239,...,-1.022547,-0.756416,-0.298642,-0.331984,-0.581821,0.411816,0.951731,5.208815,0.645626,-0.234613
213,588257.0,NaN,4688,-1.056570,-0.312389,-1.064373,-0.487588,-0.425712,-0.046165,-0.467122,...,-0.439433,-0.537441,-0.290660,-0.137926,-0.096638,-0.206585,-0.754772,-0.950994,-0.795291,-0.138598

In [7]:
f.to_csv('geneva_z_transformed.csv',header = ('INVO', 'genus_species','spec_as_int','B11','Na23','Mg26','Al27','P31','S34','K39','Ca44','Fe54','Mn55','Co59','Ni60','Cu63',
                                         'Zn66','As75','Rb85','Sr88','Mo98','Cd111'))