In [1]:
import numpy as np #Import Python Library (This is where the data is stored and pulled from the csv)
import pandas as pd # Import software library (This is a software library written for python) This library is used for data manipulation and analysis
import scipy.stats as stats #Import python library (This is used for scientific computations)

In [2]:
data0 = np.genfromtxt('geneva_y_raw_spec_as_int.csv',delimiter = ',', skip_header = 1)  # This generates data from the csv text
data0 = pd.DataFrame(data0) # This arranges the csv data into an object that pandas can use
data = data0.drop(data0.columns[0:3],axis = 1) # This removes the first three columns: plant number, plant species, and plant species as
                                               # an integer;these will be added back in the final step

In [5]:
data

,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
0,91.828727,79.436022,1912.748061,5.882495,3371.070360,2574.706720,9940.165174,14466.398220,78.712800,438.453718,0.182502,0.579481,27.983088,78.413561,0.006585,4.862209,22.391683,0.413514,0.023319
1,58.206022,40.652580,1566.902969,5.856940,3544.081320,2189.611721,9653.263267,8230.550570,54.143815,236.212667,0.091406,0.244903,23.983944,54.923095,0.009040,2.714895,13.824099,0.304084,0.020963
2,63.901449,57.636087,2274.547638,6.819170,5495.366871,2614.728325,13967.897580,12394.611400,55.249662,259.690236,0.086835,0.519297,41.153569,58.575073,0.004803,2.461506,14.488620,0.401304,0.068518
3,72.839573,72.563357,1190.390687,5.091528,3078.075354,1765.972055,7978.410800,6200.788479,41.967873,319.173261,0.111687,0.236068,14.949782,70.747574,0.009075,2.569614,6.336153,0.178760,0.015922
4,66.850648,34.508112,2073.380089,8.013734,5045.403214,2840.104738,10526.677260,8710.188433,50.256052,329.646304,0.132229,0.490120,69.027882,74.561963,0.017069,2.169312,9.098213,0.101519,0.024884
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,73.552760,100.582934,1702.405197,8.121551,6557.081779,2106.353515,12524.603240,10078.904780,64.960555,210.357172,0.134946,0.278889,26.487995,60.052907,0.007367,2.807515,10.808284,0.272505,0.020320
209,52.837115,50.424703,2317.013640,5.585417,4316.194590,2430.866591,13629.560320,13486.849460,60.112939,227.884923,0.088351,0.349421,45.929997,63.598209,0.007879,2.543901,15.396848,0.590651,0.022277
210,88.461234,74.866448,1901.131163,11.010381,4757.145687,3046.996923,14499.139850,14869.384550,66.704037,439.051010,0.157574,0.587718,82.931051,105.984075,0.020260,0.913853,16.200855,0.102829,0.026751
211,79.179090,51.390358,1466.599680,9.320131,4744.571752,2729.600334,10126.342580,10788.412550,61.858421,255.833624,0.104511,0.427264,27.725006,63.232446,0.013815,6.282494,31.449711,0.754464,0.012876
212,38.969474,17.699436,1413.523522,7.069924,4407.683239,2707.362684,13335.273690,9068.416778,28.630650,230.003818,0.089837,0.434953,50.475163,58.792397,0.008197,1.098710,10.706883,0.067636,0.016628

In [6]:
z = pd.DataFrame(np.arange(4686).reshape(213,22)) #This creates a dummy dataframe for our z value
z = z.astype('float32') #Float is used when storing data with decimal points to keep it precise 
z.drop(z.columns[0:3],axis = 1, inplace = True ) #This drops three columns in our dummy dataframe
z

,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0,21.0
1,25.0,26.0,27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0,40.0,41.0,42.0,43.0
2,47.0,48.0,49.0,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0,60.0,61.0,62.0,63.0,64.0,65.0
3,69.0,70.0,71.0,72.0,73.0,74.0,75.0,76.0,77.0,78.0,79.0,80.0,81.0,82.0,83.0,84.0,85.0,86.0,87.0
4,91.0,92.0,93.0,94.0,95.0,96.0,97.0,98.0,99.0,100.0,101.0,102.0,103.0,104.0,105.0,106.0,107.0,108.0,109.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,4579.0,4580.0,4581.0,4582.0,4583.0,4584.0,4585.0,4586.0,4587.0,4588.0,4589.0,4590.0,4591.0,4592.0,4593.0,4594.0,4595.0,4596.0,4597.0
209,4601.0,4602.0,4603.0,4604.0,4605.0,4606.0,4607.0,4608.0,4609.0,4610.0,4611.0,4612.0,4613.0,4614.0,4615.0,4616.0,4617.0,4618.0,4619.0
210,4623.0,4624.0,4625.0,4626.0,4627.0,4628.0,4629.0,4630.0,4631.0,4632.0,4633.0,4634.0,4635.0,4636.0,4637.0,4638.0,4639.0,4640.0,4641.0
211,4645.0,4646.0,4647.0,4648.0,4649.0,4650.0,4651.0,4652.0,4653.0,4654.0,4655.0,4656.0,4657.0,4658.0,4659.0,4660.0,4661.0,4662.0,4663.0
212,4667.0,4668.0,4669.0,4670.0,4671.0,4672.0,4673.0,4674.0,4675.0,4676.0,4677.0,4678.0,4679.0,4680.0,4681.0,4682.0,4683.0,4684.0,4685.0

In [7]:
for x in range(3,(data.shape[1]+3)): #This gives the dimensions of the array along the x axis
    mean = data[x].mean() #This gives the average of one column of data on the x axis
    stdev = data[x].std() #This gives the standard deviation of one column of the the x axis
    print(x,"m: ",mean,"s: ",stdev) #This prints the mean and standard deviation of the individual columns
    for y in range(data.shape[0]): #This gives the dimension of the array along the y axis
        zscore = (data[x][y] - mean)/stdev #This is the equation that gives us the z score
        z[x][y] = zscore #Assigning the name zscore to the value obtained from the equation
        if data[x][y] < 0: #If the data obtained is less than zero
            z[x][y] = "NaN" #Then it is not treated as a number
z

3 m:  75.92679166370893 s:  21.915539869192088
4 m:  70.23659033657283 s:  48.98700379976996
5 m:  1841.5504054619716 s:  515.3250973906778
6 m:  10.833314726586849 s:  17.325961708935605
7 m:  4697.549342521124 s:  1203.1337894990481
8 m:  2583.3747678685445 s:  567.7149237153909
9 m:  14033.542790732403 s:  3525.5940767183733
10 m:  10169.456888225353 s:  3763.2103311533633
11 m:  58.36411724464788 s:  20.759992742884442
12 m:  340.8257358478873 s:  125.89649054476006
13 m:  0.14242393370892018 s:  0.06262253667507753
14 m:  0.7968403194553997 s:  1.0012562641839868
15 m:  53.67687956262909 s:  32.250125265846656
16 m:  82.74856662558683 s:  32.1937719070179
17 m:  0.012123470408450694 s:  0.01420854494969449
18 m:  2.8277992425539935 s:  1.994278927770717
19 m:  12.100671134591549 s:  5.472292968213207
20 m:  0.3915100277042257 s:  0.38498391324307313
21 m:  0.029983022314554002 s:  0.019059752324079093

,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
0,0.725601,0.187793,0.138161,-0.285746,-1.102520,-0.015268,-1.161046,1.141829,0.980187,0.775462,0.639990,-0.217087,-0.796704,-0.134654,-0.389789,1.020123,1.880567,0.057154,-0.349634
1,-0.808594,-0.603916,-0.532960,-0.287221,-0.958720,-0.693593,-1.242423,-0.515227,-0.203290,-0.830945,-0.814693,-0.551245,-0.920708,-0.864312,-0.217022,-0.056614,0.314937,-0.227090,-0.473245
2,-0.548713,-0.257221,0.840241,-0.231684,0.663116,0.055228,-0.018620,0.591292,-0.150022,-0.644462,-0.887681,-0.277196,-0.388318,-0.750875,-0.515206,-0.183672,0.436371,0.025441,2.021811
3,-0.140869,0.047498,-1.263590,-0.331398,-1.346046,-1.439812,-1.717479,-1.054597,-0.789800,-0.171986,-0.490832,-0.560069,-1.200836,-0.372774,-0.214554,-0.129463,-1.053401,-0.552621,-0.737734
4,-0.414142,-0.729346,0.449871,-0.162737,0.289123,0.452216,-0.994688,-0.387772,-0.390562,-0.088799,-0.162801,-0.306335,0.475998,-0.254292,0.348082,-0.330188,-0.548666,-0.753255,-0.267504
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,-0.108326,0.619477,-0.270014,-0.156514,1.545574,-0.840248,-0.427996,-0.024062,0.317748,-1.036316,-0.119419,-0.517302,-0.843063,-0.704970,-0.334748,-0.010171,-0.236169,-0.309117,-0.506995
209,-1.053576,-0.404431,0.922647,-0.302892,-0.316968,-0.268635,-0.114586,0.881533,0.084240,-0.897093,-0.863468,-0.446858,-0.240212,-0.594847,-0.298724,-0.142356,0.602339,0.517270,-0.404289
210,0.571943,0.094512,0.115618,0.010220,0.049534,0.816646,0.132062,1.248914,0.401730,0.780207,0.241928,-0.208860,0.907103,0.721739,0.572662,-0.959719,0.749263,-0.749852,-0.169569
211,0.148401,-0.384719,-0.727600,-0.087336,0.039083,0.257569,-1.108239,0.164475,0.168319,-0.675095,-0.605415,-0.369112,-0.804706,-0.606208,0.119028,1.732303,3.535820,0.942777,-0.897571
212,-1.686352,-1.072471,-0.830596,-0.217211,-0.240926,0.218398,-0.198057,-0.292580,-1.432248,-0.880262,-0.839749,-0.361433,-0.099278,-0.744124,-0.276363,-0.867025,-0.254699,-0.841267,-0.700687

In [8]:
f = pd.DataFrame(np.arange(4686).reshape(213,22))    
f = f.astype(str) #This coverts the data into a string
f[0] = data0[0] #This means that column zero in dataframe f is coulmn zero in dataframe zero
f[1] = data0[1] #This means that column one in dataframe f is column one in dataframe zero
for x in range(3,(z.shape[1])+3): #Counts through columns
    f[x] = z[x] #Adds back the original three columns dropped and the transformed data
f

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,318684.0,NaN,2,0.725601,0.187793,0.138161,-0.285746,-1.102520,-0.015268,-1.161046,...,0.775462,0.639990,-0.217087,-0.796704,-0.134654,-0.389789,1.020123,1.880567,0.057154,-0.349634
1,588141.0,NaN,24,-0.808594,-0.603916,-0.532960,-0.287221,-0.958720,-0.693593,-1.242423,...,-0.830945,-0.814693,-0.551245,-0.920708,-0.864312,-0.217022,-0.056614,0.314937,-0.227090,-0.473245
2,588646.0,NaN,46,-0.548713,-0.257221,0.840241,-0.231684,0.663116,0.055228,-0.018620,...,-0.644462,-0.887681,-0.277196,-0.388318,-0.750875,-0.515206,-0.183672,0.436371,0.025441,2.021811
3,588378.0,NaN,68,-0.140869,0.047498,-1.263590,-0.331398,-1.346046,-1.439812,-1.717479,...,-0.171986,-0.490832,-0.560069,-1.200836,-0.372774,-0.214554,-0.129463,-1.053401,-0.552621,-0.737734
4,1583.0,NaN,90,-0.414142,-0.729346,0.449871,-0.162737,0.289123,0.452216,-0.994688,...,-0.088799,-0.162801,-0.306335,0.475998,-0.254292,0.348082,-0.330188,-0.548666,-0.753255,-0.267504
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,588392.0,NaN,4578,-0.108326,0.619477,-0.270014,-0.156514,1.545574,-0.840248,-0.427996,...,-1.036316,-0.119419,-0.517302,-0.843063,-0.704970,-0.334748,-0.010171,-0.236169,-0.309117,-0.506995
209,588391.0,NaN,4600,-1.053576,-0.404431,0.922647,-0.302892,-0.316968,-0.268635,-0.114586,...,-0.897093,-0.863468,-0.446858,-0.240212,-0.594847,-0.298724,-0.142356,0.602339,0.517270,-0.404289
210,588371.0,NaN,4622,0.571943,0.094512,0.115618,0.010220,0.049534,0.816646,0.132062,...,0.780207,0.241928,-0.208860,0.907103,0.721739,0.572662,-0.959719,0.749263,-0.749852,-0.169569
211,588149.0,NaN,4644,0.148401,-0.384719,-0.727600,-0.087336,0.039083,0.257569,-1.108239,...,-0.675095,-0.605415,-0.369112,-0.804706,-0.606208,0.119028,1.732303,3.535820,0.942777,-0.897571
212,588257.0,NaN,4666,-1.686352,-1.072471,-0.830596,-0.217211,-0.240926,0.218398,-0.198057,...,-0.880262,-0.839749,-0.361433,-0.099278,-0.744124,-0.276363,-0.867025,-0.254699,-0.841267,-0.700687

In [9]:
f.to_csv('geneva_y_transformed.csv',header = ('INVO', 'genus_species','spec_as_int','B11','Na23','Mg26','Al27','P31','S34','K39','Ca44','Fe54','Mn55','Co59','Ni60','Cu63',
                                         'Zn66','As75','Rb85','Sr88','Mo98','Cd111'))