In [11]:
import numpy as np #Import Python Library (This is where the data is stored and pulled from the csv)
import pandas as pd # Import software library (This is a software library written for python) This library is used for data manipulation and analysis
import scipy.stats as stats #Import python library (This is used for scientific computations)

In [12]:
data0 = np.genfromtxt('geneva_x_raw_spec_as_int.csv',delimiter = ',', skip_header = 1)  # This generates data from the csv text
data0 = pd.DataFrame(data0) # This arranges the csv data into an object that pandas can use
data = data0.drop(data0.columns[0:3],axis = 1) # This removes the first three columns: plant number, plant species, and plant species as
                                               # an integer;these will be added back in the final step

In [13]:
data

,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
0,94.737452,196.644672,1776.847433,14.015541,6214.957396,1986.070463,18823.60057,5107.996944,45.755582,191.923742,0.081735,0.811444,33.255243,95.859746,0.005128,16.256776,5.981147,0.278855,0.024450
1,23.352362,131.009202,1166.801218,15.981347,5660.589666,1305.737926,15284.87070,3971.658387,40.226177,101.724123,0.048140,0.343131,33.814473,69.386864,0.017477,7.492277,3.537671,0.156314,0.060345
2,137.680886,111.022071,1976.897836,26.302390,7208.531961,2512.636791,20787.04128,5653.053084,65.567369,146.973893,0.063966,0.277827,58.400894,83.124578,0.004849,7.214685,3.383637,0.297982,0.017739
3,18.207032,58.447077,1469.811734,24.007341,5342.222323,2400.683753,16094.43910,3800.777526,60.854345,218.874289,0.099867,0.416359,55.600415,120.534218,0.010221,11.923196,1.183187,0.171235,0.038915
4,58.775194,119.388231,1349.136877,67.323999,5412.124249,2412.665543,17162.72458,2307.560196,91.539069,357.633934,0.169915,0.658896,68.828553,153.686687,0.060230,7.493530,1.004368,0.194630,0.021889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,67.741168,304.314091,1569.374659,16.677154,6748.686105,2350.680570,20042.69489,4278.399563,53.814193,143.035195,0.155757,0.495990,40.642401,117.175517,0.003763,6.422968,3.711751,0.196167,0.016556
209,103.184159,199.080237,2406.872272,19.159328,6836.833305,2370.725889,17012.25025,12898.808280,74.608908,254.304705,0.124091,0.567154,69.885326,138.910669,0.009014,5.972465,11.572697,0.725383,0.058088
210,30.245000,261.985064,1193.187667,26.138933,5326.504359,1997.043188,12438.46572,6332.824452,58.684089,380.402461,0.150284,0.542041,69.756006,122.545788,0.027804,1.433240,5.714804,0.089911,0.034804
211,34.208841,203.622133,1447.813622,15.960988,5894.753089,2327.943324,15017.33769,7088.181973,59.082861,208.111940,0.094035,0.683960,35.765968,107.140420,0.013674,12.448808,15.016234,0.419732,0.014924
212,85.332953,219.016193,1238.272020,18.859439,5045.123961,2140.332114,16921.28096,4448.331790,36.105131,236.603559,0.090336,0.311027,43.430994,104.619752,0.015108,2.710181,3.156244,0.059054,0.004898

In [14]:
z = pd.DataFrame(np.arange(4686).reshape(213,22)) #This creates a dummy dataframe for our z value
z = z.astype('float32') #Float is used when storing data with decimal points to keep it precise 
z.drop(z.columns[0:3],axis = 1, inplace = True ) #This drops three columns in our dummy dataframe
z

,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0,21.0
1,25.0,26.0,27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0,40.0,41.0,42.0,43.0
2,47.0,48.0,49.0,50.0,51.0,52.0,53.0,54.0,55.0,56.0,57.0,58.0,59.0,60.0,61.0,62.0,63.0,64.0,65.0
3,69.0,70.0,71.0,72.0,73.0,74.0,75.0,76.0,77.0,78.0,79.0,80.0,81.0,82.0,83.0,84.0,85.0,86.0,87.0
4,91.0,92.0,93.0,94.0,95.0,96.0,97.0,98.0,99.0,100.0,101.0,102.0,103.0,104.0,105.0,106.0,107.0,108.0,109.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,4579.0,4580.0,4581.0,4582.0,4583.0,4584.0,4585.0,4586.0,4587.0,4588.0,4589.0,4590.0,4591.0,4592.0,4593.0,4594.0,4595.0,4596.0,4597.0
209,4601.0,4602.0,4603.0,4604.0,4605.0,4606.0,4607.0,4608.0,4609.0,4610.0,4611.0,4612.0,4613.0,4614.0,4615.0,4616.0,4617.0,4618.0,4619.0
210,4623.0,4624.0,4625.0,4626.0,4627.0,4628.0,4629.0,4630.0,4631.0,4632.0,4633.0,4634.0,4635.0,4636.0,4637.0,4638.0,4639.0,4640.0,4641.0
211,4645.0,4646.0,4647.0,4648.0,4649.0,4650.0,4651.0,4652.0,4653.0,4654.0,4655.0,4656.0,4657.0,4658.0,4659.0,4660.0,4661.0,4662.0,4663.0
212,4667.0,4668.0,4669.0,4670.0,4671.0,4672.0,4673.0,4674.0,4675.0,4676.0,4677.0,4678.0,4679.0,4680.0,4681.0,4682.0,4683.0,4684.0,4685.0

In [15]:
for x in range(3,(data.shape[1]+3)): #This gives the dimensions of the array along the x axis
    mean = data[x].mean() #This gives the average of one column of data on the x axis
    stdev = data[x].std() #This gives the standard deviation of one column of the the x axis
    print(x,"m: ",mean,"s: ",stdev) #This prints the mean and standard deviation of the individual columns
    for y in range(data.shape[0]): #This gives the dimension of the array along the y axis
        zscore = (data[x][y] - mean)/stdev #This is the equation that gives us the z score
        z[x][y] = zscore #Assigning the name zscore to the value obtained from the equation
        if data[x][y] < 0: #If the data obtained is less than zero
            z[x][y] = "NaN" #Then it is not treated as a number
z

3 m:  105.41411872399054 s:  70.88301440956413
4 m:  221.65057872892035 s:  143.90517278099213
5 m:  1592.7760789037557 s:  333.212599865932
6 m:  20.629450678971814 s:  8.538729766239161
7 m:  5796.119500488267 s:  831.2325551323902
8 m:  2264.2115201173706 s:  457.3371087375541
9 m:  16985.076778821604 s:  2360.89757350926
10 m:  5708.816759596245 s:  2792.224720615056
11 m:  55.243467012723 s:  16.474121746228857
12 m:  272.69204762276996 s:  137.14775684902708
13 m:  0.1248759968591549 s:  0.0636205307936663
14 m:  0.9920279330187797 s:  1.2122159985811458
15 m:  61.037493463004665 s:  28.60336332119884
16 m:  132.59506704469487 s:  83.5377610449614
17 m:  0.017291919896713612 s:  0.023163195269186882
18 m:  5.712304938361498 s:  3.3262304364623487
19 m:  4.551343845666668 s:  3.0826569345190804
20 m:  0.3344515690469483 s:  0.32681480587995215
21 m:  0.029670246511737098 s:  0.022255681367097345

,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
0,-0.150624,-0.173767,0.552414,-0.774578,0.503876,-0.608175,0.778739,-0.215176,-0.575927,-0.588915,-0.678095,-0.148970,-0.971293,-0.439745,-0.525148,3.170096,0.463822,-0.170116,-0.234562
1,-1.157707,-0.629869,-1.278388,-0.544355,-0.163047,-2.095770,-0.720152,-0.622141,-0.911568,-1.246597,-1.206156,-0.535298,-0.951742,-0.756642,0.008004,0.535132,-0.328831,-0.545072,1.378271
2,0.455212,-0.768760,1.152783,0.664377,1.699178,0.543199,1.610389,-0.019971,0.626674,-0.916662,-0.957400,-0.589170,-0.092178,-0.592193,-0.537180,0.451676,-0.378799,-0.111591,-0.536109
3,-1.230296,-1.134104,-0.369027,0.395596,-0.546053,0.298406,-0.377245,-0.683340,0.340587,-0.392407,-0.393089,-0.474889,-0.190085,-0.144376,-0.305267,1.867246,-1.092615,-0.499415,0.415369
4,-0.657970,-0.710623,-0.731182,5.468559,-0.461959,0.324605,0.075246,-1.218117,2.203189,0.619346,0.707925,-0.274812,0.272383,0.252480,1.853715,0.535509,-1.150623,-0.427830,-0.349650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,-0.531481,0.574430,-0.070230,-0.462867,1.145969,0.189071,1.295108,-0.512286,-0.086759,-0.945381,0.485400,-0.409200,-0.713031,-0.184582,-0.584091,0.213654,-0.272360,-0.423129,-0.589257
209,-0.031460,-0.156842,2.443173,-0.172171,1.252013,0.232901,0.011510,2.575005,1.175507,-0.134070,-0.012333,-0.350494,0.309328,0.075602,-0.357358,0.078215,2.277695,1.196186,1.276882
210,-1.060467,0.280285,-1.199200,0.645234,-0.564962,-0.584183,-1.925798,0.223480,0.208850,0.785360,0.399363,-0.371211,0.304807,-0.120296,0.453840,-1.286461,0.377421,-0.748253,0.230684
211,-1.004546,-0.125280,-0.435045,-0.546740,0.118659,0.139354,-0.833471,0.494002,0.233056,-0.470880,-0.484763,-0.254136,-0.883516,-0.304708,-0.156203,2.025266,3.394763,0.260945,-0.662592
212,-0.283300,-0.018306,-1.063897,-0.207292,-0.903472,-0.270871,-0.027022,-0.451427,-1.161721,-0.263136,-0.542902,-0.561782,-0.615539,-0.334882,-0.094302,-0.902560,-0.452564,-0.842671,-1.113086

In [16]:
f = pd.DataFrame(np.arange(4686).reshape(213,22))    
f = f.astype(str) #This coverts the data into a string
f[0] = data0[0] #This means that column zero in dataframe f is coulmn zero in dataframe zero
f[1] = data0[1] #This means that column one in dataframe f is column one in dataframe zero
for x in range(3,(z.shape[1])+3): #Counts through columns
    f[x] = z[x] #Adds back the original three columns dropped and the transformed data
f

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,318684.0,NaN,2,-0.150624,-0.173767,0.552414,-0.774578,0.503876,-0.608175,0.778739,...,-0.588915,-0.678095,-0.148970,-0.971293,-0.439745,-0.525148,3.170096,0.463822,-0.170116,-0.234562
1,588141.0,NaN,24,-1.157707,-0.629869,-1.278388,-0.544355,-0.163047,-2.095770,-0.720152,...,-1.246597,-1.206156,-0.535298,-0.951742,-0.756642,0.008004,0.535132,-0.328831,-0.545072,1.378271
2,588646.0,NaN,46,0.455212,-0.768760,1.152783,0.664377,1.699178,0.543199,1.610389,...,-0.916662,-0.957400,-0.589170,-0.092178,-0.592193,-0.537180,0.451676,-0.378799,-0.111591,-0.536109
3,588448.0,NaN,68,-1.230296,-1.134104,-0.369027,0.395596,-0.546053,0.298406,-0.377245,...,-0.392407,-0.393089,-0.474889,-0.190085,-0.144376,-0.305267,1.867246,-1.092615,-0.499415,0.415369
4,1583.0,NaN,90,-0.657970,-0.710623,-0.731182,5.468559,-0.461959,0.324605,0.075246,...,0.619346,0.707925,-0.274812,0.272383,0.252480,1.853715,0.535509,-1.150623,-0.427830,-0.349650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,588392.0,NaN,4578,-0.531481,0.574430,-0.070230,-0.462867,1.145969,0.189071,1.295108,...,-0.945381,0.485400,-0.409200,-0.713031,-0.184582,-0.584091,0.213654,-0.272360,-0.423129,-0.589257
209,588391.0,NaN,4600,-0.031460,-0.156842,2.443173,-0.172171,1.252013,0.232901,0.011510,...,-0.134070,-0.012333,-0.350494,0.309328,0.075602,-0.357358,0.078215,2.277695,1.196186,1.276882
210,588371.0,NaN,4622,-1.060467,0.280285,-1.199200,0.645234,-0.564962,-0.584183,-1.925798,...,0.785360,0.399363,-0.371211,0.304807,-0.120296,0.453840,-1.286461,0.377421,-0.748253,0.230684
211,588149.0,NaN,4644,-1.004546,-0.125280,-0.435045,-0.546740,0.118659,0.139354,-0.833471,...,-0.470880,-0.484763,-0.254136,-0.883516,-0.304708,-0.156203,2.025266,3.394763,0.260945,-0.662592
212,588257.0,NaN,4666,-0.283300,-0.018306,-1.063897,-0.207292,-0.903472,-0.270871,-0.027022,...,-0.263136,-0.542902,-0.561782,-0.615539,-0.334882,-0.094302,-0.902560,-0.452564,-0.842671,-1.113086

In [17]:
f.to_csv('brsgv.csv',header = ('INVO', 'genus_species','spec_as_int','B11','Na23','Mg26','Al27','P31','S34','K39','Ca44','Fe54','Mn55','Co59','Ni60','Cu63',
                                         'Zn66','As75','Rb85','Sr88','Mo98','Cd111'))